name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to cPanel
      env:
        FTP_HOST: ftp.wpdemo2.com
        FTP_USER: ${{secrets.FTP_USERNAME}}
        FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
      run: |
        lftp -c "set ftp:ssl-allow no; open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST; mirror -R -e -v --ignore-time --parallel=10 --no-perms ." public_html/new"