name: Deploy to FTP server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Zip code
      run: zip -r code.zip .
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: code.zip
        path: code.zip
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: code.zip
    - name: Unzip code
      run: unzip code.zip
    - name: Deploy to FTP
      run: |
        ftp-upload -h ${{ secrets.FTP_SERVER }} -u ${{ secrets.FTP_USERNAME }} -p ${{ secrets.FTP_PASSWORD }} -d /home/wpdemo2c/wpdemo2.com/cicdtest/ -l code
