name: Deploy to FTP server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: ftp-action
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.wpdemo2.com
        username: wpdemo2c
        password: 612m171c83DX_3p
        server-dir: ./public_html/new/
